from decimal import Decimal
from pathlib import Path

from steam_market_history.acquisition import classify
from steam_market_history.parser import load_history_json, parse_transactions
from steam_market_history.stats import summarize, summarize_by_game

FIXTURES = Path(__file__).parent / "fixtures"

# Generated by scripts/generate_multi_currency_fixture.py - one currency per
# market type, but real acquisition variety (confirmed drops, a matched
# trade, an ambiguous case, a still-held item).
MULTI_CURRENCY = FIXTURES / "multi_currency_history.json"

# Generated by scripts/generate_multi_currency_stress_fixture.py - every
# market type in every currency, deliberately unrealistic, purely to stress
# "currencies are never mixed."
STRESS = FIXTURES / "multi_currency_stress_history.json"


def _load(path: Path):
    return classify(parse_transactions(load_history_json(path)))


def test_multi_currency_fixture_keeps_four_currencies_separate() -> None:
    totals = summarize(_load(MULTI_CURRENCY))

    assert set(totals) == {"£", "€", "$", "¥"}
    assert totals["£"].net_profit == Decimal("0.53")
    assert totals["€"].net_profit == Decimal("4.35")
    assert totals["$"].net_profit == Decimal("0.50")
    assert totals["¥"].net_profit == Decimal("190")


def test_multi_currency_fixture_each_game_has_exactly_one_currency() -> None:
    by_game = summarize_by_game(_load(MULTI_CURRENCY))

    assert set(by_game["Counter-Strike 2"].totals_by_currency) == {"£"}
    assert set(by_game["Rust"].totals_by_currency) == {"€"}
    assert set(by_game["PUBG: BATTLEGROUNDS"].totals_by_currency) == {"$"}
    assert set(by_game["Team Fortress 2"].totals_by_currency) == {"¥"}


def test_stress_fixture_every_game_has_every_currency() -> None:
    by_game = summarize_by_game(_load(STRESS))

    assert set(by_game) == {
        "Counter-Strike 2",
        "Rust",
        "PUBG: BATTLEGROUNDS",
        "Team Fortress 2",
    }
    for game, summary in by_game.items():
        assert set(summary.totals_by_currency) == {"£", "€", "$", "¥"}, game


def test_stress_fixture_every_bucket_has_the_same_predictable_shape() -> None:
    by_game = summarize_by_game(_load(STRESS))

    for game, summary in by_game.items():
        for currency, totals in summary.totals_by_currency.items():
            assert totals.sold_count == 1, (game, currency)
            assert totals.purchased_count == 1, (game, currency)
            assert totals.sold_total == Decimal("2.50"), (game, currency)
            assert totals.purchased_total == Decimal("1.00"), (game, currency)
            assert totals.net_profit == Decimal("1.50"), (game, currency)


def test_stress_fixture_no_currency_bleeds_into_another() -> None:
    # The strongest direct check: sum every bucket's sold_total per
    # currency and confirm it only ever includes that currency's own
    # transactions - 4 games x £2.50 = £10.00, same for every currency.
    totals = summarize(_load(STRESS))

    for currency in ("£", "€", "$", "¥"):
        assert totals[currency].sold_total == Decimal("10.00")
        assert totals[currency].purchased_total == Decimal("4.00")
