from decimal import Decimal
from pathlib import Path

from steam_market_history.acquisition import classify
from steam_market_history.parser import load_history_json, parse_transactions
from steam_market_history.stats import cumulative_series

# Generated by scripts/generate_drop_lines_fixture.py - one currency, three
# items, deliberately built for a wide confirmed/ambiguous spread so the
# ledger's three drop-revenue chart lines (SML-33) are visually
# distinguishable, unlike earlier narrow-spread manual testing.
FIXTURE = Path(__file__).parent / "fixtures" / "drop_lines_history.json"


def _load():
    return classify(parse_transactions(load_history_json(FIXTURE)))


def test_drop_lines_fixture_final_cumulative_totals() -> None:
    series = cumulative_series(_load())
    final = series["£"][-1]

    assert final.cumulative_confirmed_drop_revenue == Decimal("0.45")
    assert final.cumulative_ambiguous_ceiling == Decimal("17.45")
    assert final.cumulative_best_guess_drop_revenue == Decimal("5.95")


def test_drop_lines_fixture_confirmed_floor_is_monotonically_nondecreasing() -> None:
    series = cumulative_series(_load())
    floor_values = [point.cumulative_confirmed_drop_revenue for point in series["£"]]

    assert floor_values == sorted(floor_values)


def test_drop_lines_fixture_ceiling_never_below_best_guess_or_floor() -> None:
    series = cumulative_series(_load())

    for point in series["£"]:
        assert point.cumulative_ambiguous_ceiling >= point.cumulative_best_guess_drop_revenue
        assert point.cumulative_best_guess_drop_revenue >= point.cumulative_confirmed_drop_revenue
